---
title: "turnover"
author: "Adam Wawro"
date: "6/11/2020"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=FALSE}
library(tidyverse)
library(ggridges)
library(viridis)
library(sf)
```

```{r cache=TRUE, include=FALSE}
results_station_clean <- readRDS("../output/clean/results_station_clean.rds")
results_candidate_clean <- readRDS("../output/clean/results_candidate_clean.rds")
results_slate_clean <- readRDS("../output/clean/results_slate_clean.rds")
results_candidate_full <- readRDS("../output/clean/results_candidate_full.rds")
map_powiaty <- readRDS("../output/clean/map_powiaty.rds")
map_wojewodztwa <- readRDS("../output/clean/map_wojewodztwa.rds")
powiaty_table <- readRDS("../output/clean/powiaty_table.rds")
```

## The Sejm elections in Poland, 2019

### Voter turnover

By voivodeship

```{r}
turnover_woj <- results_station_clean %>%
  group_by(wojewodztwo) %>%
  summarize(turnover = sum(wydane_karty) / sum(wyborcow_uprawnionych) * 100, .groups = 'drop')

map_wojewodztwa %>%
  left_join(turnover_woj, by = c("nazwa" = "wojewodztwo")) %>%
  ggplot() +
    geom_sf(aes(fill = turnover), size = 0.1, color = "white") +
    scale_fill_viridis(limits = c(46,78), breaks = c(50, 55, 60, 65, 70, 75), name = "turnover / %", option = "E") +
    theme_void() +
    theme(legend.position = "right")
```

By powiat

```{r}
turnover_pow <- results_station_clean %>%
  group_by(powiat) %>%
  summarize(turnover = sum(wydane_karty) / sum(wyborcow_uprawnionych) * 100, .groups = 'drop')

map_powiaty %>%
  left_join(turnover_pow, by = c("nazwa" = "powiat")) %>%
  ggplot() +
    geom_sf(aes(fill = turnover)) +
    geom_sf(data = map_wojewodztwa, size = 0.1, fill = NA, color = "white") +
    scale_fill_viridis(limits = c(46,78), breaks = c(50, 55, 60, 65, 70, 75), name = "turnover / %", option = "E") +
    theme_void() +
    theme(legend.position = "right")
```

Urban vs rural by voivodeship

```{r}
results_station_clean %>%
  filter(typ_obszaru %in% c("miasto", "wieś")) %>%
  ggplot(aes(x=wojewodztwo, y=(wydane_karty / wyborcow_uprawnionych * 100), fill = typ_obszaru)) +
  stat_boxplot(outlier.shape = NA) +
  labs(y="turnover / %", x="voivodeship") +
  scale_fill_discrete(name = "area type", labels = c("urban", "rural")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

By powiat density

```{r}
results_station_clean %>%
  filter(typ_obszaru %in% c("miasto", "wieś")) %>%
  group_by(powiat) %>%
  summarize(turnover = sum(wydane_karty) / sum(wyborcow_uprawnionych) * 100, n_stations = n(), n_voters = sum(wyborcow_uprawnionych), .groups = 'drop') %>%
  left_join(powiaty_table, by = "powiat") %>%
  mutate(area_perstation = powierzchnia / n_stations) %>%
  ggplot(aes(x = area_perstation, y = turnover)) +
    geom_point() +
    geom_smooth(formula = (y ~ x), method = 'lm') +
    labs(x = "area per station / km2", y = "turnover / %") +
    expand_limits(y = c(40,80))
```

By registered voters per station

```{r, fig.height = 7}
results_station_clean %>%
  filter(typ_obszaru %in% c("miasto", "wieś")) %>%
  ggplot(aes(x = wyborcow_uprawnionych, y = (wydane_karty / wyborcow_uprawnionych * 100))) +
    stat_density2d(data = results_station_clean[results_station_clean$typ_obszaru == "miasto",], color = "blue", alpha = 0.5) +
    stat_density2d(data = results_station_clean[results_station_clean$typ_obszaru == "wieś",], color = "red", alpha= 0.5) +
    labs(x = "registered voters per station", y = "turnover / %") +
    expand_limits(y = c(0,100)) +
    facet_wrap("wojewodztwo")
```

